name: directcode
version: 1.0.0
description: DirectCode Site
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  core_elements: '>=0.2.2+1 <0.3.0'
  paper_elements: '>=0.3.0 <0.5.0'
  polymer: '>=0.14.2+1 <0.15.0'
  github: '>=1.3.1 <1.5.0'
transformers:
- polymer:
    entry_points: web/index.html
