name: directcode
version: 1.0.0
description: DirectCode Site
dependencies:
  ansicolor: '>=0.0.9 <0.1.0'
  browser: '>=0.10.0+2 <0.11.0'
  core_elements: '>=0.1.1+2 <0.1.5'
  paper_elements: '>=0.1.0+2 <0.1.5'
  path: '>=1.3.0 <2.0.0'
  polymer: '>=0.12.1 <0.12.5'
  github: '>=0.5.9 <0.6.0'
transformers:
- polymer:
    entry_points: web/index.html
    csp: true
