name: directcode
version: 1.0.0
description: DirectCode Site
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  core_elements: '>=0.2.0+1 <0.3.0'
  paper_elements: '>=0.1.1+2 <0.2.0'
  polymer: '>=0.13.0 <0.14.0'
  github: '>=1.3.0 <1.5.0'
transformers:
- polymer:
    entry_points: web/index.html
    csp: true
